[acoustics]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256


[inferencer]
path = "audio_preprocessing.FullSubNet.inferencer.Inferencer"
type = "full_band_crm_mask"

[inferencer.args]
n_neighbor = 15


[dataset]
path = "audio_preprocessing.FullSubNet.dataset_inference.Dataset"

[dataset.args]
dataset_dir_list = [
    "dataset/raw"
]
sr = 32000


[model]
path = "audio_preprocessing.FullSubNet.fullsubnet.model.Model"

[model.args]
sb_num_neighbors = 15
fb_num_neighbors = 0
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2

